wso2/reference-implementation-consumerdatastandards-au

toolkits/ob-bi/carbon-home/deployment/siddhi-files/GetInvocationDataApp.siddhi

> This PR changes hostname placeholder to BI_HOSTNAME in GetInvocationDataApp.siddhi
Related PR: 
- https://github.com/wso2/reference-implementation-consumerdatastandards-au/pull/5

Change hostname placeholder to BI_HOSTNAME in GetInvocationDataApp

---

toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

> $subject due to the introduction of the following proxies: https://github.com/wso2/reference-implementation-consumerdatastandards-au/tree/main/toolkits/ob-apim/carbon-home/repository/deployment/server/synapse-configs/default/api 
------
6. [ ] Have you verify the PR does't commit any keys, passwords, tokens, usernames, or …

Added config changes related to proxy API changes

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/dcr/model/CDSRegistrationRequest.java
components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/dcr/model/CDSSoftwareStatementBody.java
components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/dcr/utils/ValidationUtils.java

> This PR fixes issues in imports in DCR module
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?

Fix DCR import issues

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/retrieval/CDSAccountMaskingRetrievalStep.java
components/org.wso2.openbanking.cds.consent.extensions/src/test/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/retrieval/CDSAccountMaskingRetrievalStepTest.java

> This PR checks the app is regulatory to execute CDSAccountMaskingRetrievalStep.
**Issue link:** 
- https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/519
------
2. [X] Ran checkstyle plugin with pull request in place.
3. [X] Ran Findbugs plugin with pull request in place.
4. [X] Ran FindSecurityBugs plugin and verified report.
5. [X] Formatted code according to WSO2 code style.
6. [X] Have you verify the PR does't commit any keys, passwords, tokens, usernames, or other secrets?
8. [X] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [X] Written unit tests. …

Check if app is regulatory for consent CDSAccountMaskingRetrievalStep

---

components/org.wso2.openbanking.cds.demo.backend/src/main/webapp/WEB-INF/web.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/src/main/webapp/WEB-INF/web.xml

> Recently the APIM team removed all the spring dependencies from the APIM base product due to a security fix and with that removal all the webapps needed to be moved out of the spring usage. This PR does the required changes in order to avoid using spring dependencies.
**Issue link:** 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/7543
**Applicable Labels:** OB 3.0.0, CDS Toolkit
------
2. [X] Ran checkstyle plugin with pull request in place.
3. [X] Ran Findbugs plugin with pull request in place.
4. [X] Ran FindSecurityBugs plugin and verified report.
5. [X] Formatted code according to WSO2 code style.
6. …

Removing spring reference from cds demo backend and metrics webapps

---

toolkits/ob-apim/carbon-home/repository/deployment/server/synapse-configs/default/api/_TokenAPI_.xml

> This fix is to engage GatewayClientAuthenticationHandler in token call which attaches the transport certificate to a request header in the request passed to IS side. 
------
7. [ ] Migration scripts …

Update TokenAPI.xml to engage GatewayClientAuthenticationHandler

---

toolkits/ob-bi/carbon-home/deployment/siddhi-files/APIRawDataSubmissionApp.siddhi

> The root cause for the issue is not using a window in stream joining operation, which is a must according to the siddhi documentation
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/144*
------ …

Fix Average Response and Performance metrics not getting updated

---

toolkits/ob-bi/bin/configure.sh

> This PR includes fix to replace placeholders of the newly added GetInvocationDataApp.siddhi when the obbi configure.sh is run
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/132*
------
7. [ ] …

Update obbi configure script

---

toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

> Prevent OBPrivateKeyJWTClientAuthenticator from engaging
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/140*
------
8. [ ] Have you followed …

Fix attaching incorrect authenticator for par request

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/retrieval/CDSDataClusterRetrievalStep.java
components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/utils/CDSDataRetrievalUtil.java
components/org.wso2.openbanking.cds.consent.extensions/src/test/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/retrieval/CDSDataClusterRetrievalStepTests.java

> Mentioned in the issue link.
**Issue link:** https://github.com/wso2/reference-implementation-consumerdatastandards-au/issues/29
**Doc Issue:** N/A
**Applicable Labels:** CDS toolkit
------
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [x] Written …

Fix data cluster display issue in CDs toolkit

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/authenticator/util/CDSJWTValidator.java

> Fixes the error came when performing the arrangement revocation request without the ```iat``` value in the client assertion.
**Issue link:** https://github.com/wso2/reference-implementation-consumerdatastandards-au/issues/31
**Doc Issue:** N/A
**Applicable Labels:** CDS toolkit
------
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering …

Fix the arrangement revocation issue when client assertion doesn't have ```iat``` value

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

> This PR is to prepare for the 1.0.1 release.

Prepare for 1.0.1 release

---

pom.xml

> Explain  in a few lines the purpose of this pull request
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/188
**Doc Issue:** N/A
**Applicable Labels:** CDS toolkit
------
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [ ] …

Change json smart version to a version range

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [ ] Written unit tests.
2. [ ] Documented test scenarios(link available in guides).
3. [ ] Written automation tests (link available in guides).
4. [ ] Verified tests in multiple database …

Prepare for the development iteration 1.0.2

---

pom.xml

Reverts wso2/reference-implementation-consumerdatastandards-au#35

Revert "Change json smart version to a version range"

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/grant/type/handlers/CDSAuthorizationCodeGrantHandler.java

> $subject
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/192
**Doc Issue:** N/A
**Applicable Labels:** CDS toolkit
------
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [x] Written unit tests.
2. [ ] Documented test …

Fix refresh token validity period issue

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

> Update artifact versions to 1.0.2
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering …

Preapare for release 1.0.2

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/dcr/model/CDSRegistrationRequest.java
toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

> This PR adds the required changes to the Registration Request Object to make the iat, jti and exp claims mandatory in the DCR request. Config changes are also included.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/199*
------
6. [ ] Have you verify the PR does't commit any keys, passwords, …

Make iat, jti and exp claims mandatory in DCR request

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

> Update pom versions to 1.0.3

Preapare for release 1.0.3

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for the development iteration 1.0.4

---

components/org.wso2.openbanking.cds.common/src/main/java/org/wso2/openbanking/cds/common/config/OpenBankingCDSConfigParser.java
components/org.wso2.openbanking.cds.common/src/main/java/org/wso2/openbanking/cds/common/utils/CommonConstants.java
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/retrieval/CDSProfileListRetrievalStep.java
components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authservlet/impl/OBCDSAuthServletImpl.java
toolkits/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking-cds.xml.j2
toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

> This PR contains the fix to get the customer profile type using cookies sent
**Issue link:** *https://github.com/wso2-enterprise/wso2-ob-internal/issues/916*
------
8. [ ] …

Getting customer profile type using cookie

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Preapare for release 1.0.4

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for the development iteration 1.0.5

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/authenticator/CDSBasePrivateKeyJWTClientAuthenticator.java

> Changed order of validation to validate mandatory "sub" claim before validating with the client ID
**Issue link:** *https://github.com/wso2-enterprise/wso2-ob-internal/issues/925*
------
7. [ ] Migration scripts written (if …

Changed order of validation to avoid server error

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

> Prepare for the development iteration 1.0.6
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [ ] Written unit tests.
2. [ ] Documented test scenarios(link available in guides).
3. [ ] Written automation tests (link available in guides).
4. [ ] Verified …

Prepare for the development iteration 1.0.6

---

toolkits/ob-apim/pom.xml
toolkits/ob-is/pom.xml

> There is a error while building with `-P solution` for the first time since it tries to delete `dropins` folder which does not exist, with this PR that failure on error is skipped.
------
7. [ ] …

Fix error while building the repo with -P solution

---

toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

> $subject, this is happening because of a base product change done with this PR https://github.com/wso2-support/identity-inbound-auth-oauth/pull/1609, they have introduced a config to preserver the previous behaviour hence adding this to the default toolkit toml
**Issue link:** *https://github.com/wso2-enterprise/wso2-ob-internal/issues/924*
------
5. [ ] Formatted code …

Fix for not displaying name data cluster when profile scope is present

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for release 1.0.6

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for the development iteration 1.0.7

---

.github/workflows/create-release-tag.yaml

> When this workflow is run manually, pom versions will be updated according to the given inputs and a new tag will be created. Version update commit will be created with the username of the user who is triggering the workflow.
------
6. [ ] Have you verify the PR does't commit any keys, passwords, tokens, usernames, or other …

Add github workflow to update pom versions and create release tags

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for 1.1.0 release

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for the development iteration 1.1.1

Prepare for the development iteration 1.1.1

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for 1.1.1 release

---

toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

> $subject based on [1]
[1] https://consumerdatastandardsaustralia.github.io/standards/#client-registration
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/238*
------
7. [ ] Migration scripts …

Added SSA unmodifiable metadata config based on the CDS specification

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for release 1.1.2

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for the development iteration 1.1.3

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/persist/CDSConsentPersistStep.java
components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/utils/CDSConsentPersistUtil.java
components/org.wso2.openbanking.cds.consent.extensions/src/test/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/persist/CDSBusinessAccountConsentPersistenceStepTest.java
components/org.wso2.openbanking.cds.consent.extensions/src/test/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/persist/CDSJointAccountConsentPersistenceStepTest.java

> This PR prevents persisting duplicate consent mappings by checking and avoiding duplicate consent mappings for the same memberId across multiple accounts.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/255
------
6. [x] Have you verify the PR does't commit any keys, passwords, tokens, usernames, …

Prevent persisting duplicate consent mappings

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authservlet/impl/OBCDSAuthServletImpl.java

> In the authorization flow, joint accounts and secondary accounts are incorrectly displayed as selectable, even when the isEligible flag is set to false in the sharable accounts response.
> To address this, the isEligible field check should be prioritized to ensure only eligible accounts are displayed during the account selection process
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/251
------
4. [x] …

Invoke isEligible field check to filter accounts in authorization flow

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/listener/application/CDSApplicationUpdaterImpl.java
components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/metadata/periodical/updater/service/dataholder/responsibility/InvalidateConsentsResponsibility.java

> $subject is due to the method `revokeExistingApplicableConsents` is only revoking consents that were created by the admin user
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/253*
------
7. [ ] …

Fix for recipient count not updating when an active ADR is deleted

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for release v1.1.3

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for the development iteration 1.1.4

---

toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/extensions/toolkit-data-extension.jsp
toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/identifierauth.jsp

> When the back button is clicked from the account selection page an error is returned, this PR does the changes required to give the same behaviour as in OB2 in the CDS toolkit by navigating back to the SMS OTP page without throwing an error.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/228*
------
5. [x] Formatted code according to WSO2 code …

Fixed back button issue in SMS OTP page

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for release v1.1.4

---

toolkits/ob-is/carbon-home/repository/deployment/server/webapps/ob#authenticationendpoint/oauth2_authz_displayconsent.jsp

> This PR adds the capability to display the sharing_duration value as minutes in the consent page.
**Issue link:** 
- https://github.com/wso2/financial-services-accelerator/issues/304
------
7. [ ] Migration scripts written …

Display the sharing_duration value as minutes in the consent page

---

toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/extensions/toolkit-consent-skip.jsp
toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/extensions/toolkit-data-extension.jsp
toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/extensions/toolkit-disclaimer.jsp
toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/identifierauth.jsp

> This PR adds two cookies as a fallback option. If the user presses the browser back button and the `spDetails` and `callbackURL` are not available in the session, the value can be retrieved from this cookie.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/228
------
6. [x] Have you verify the PR …

Ensure Client Name Displays Correctly in Disclaimer After Browser Back Button Press

---

components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

Prepare for release v1.1.5

---

toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/extensions/toolkit-consent-skip.jsp
toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/extensions/toolkit-disclaimer.jsp
toolkits/ob-is/carbon-home/repository/deployment/server/webapps/authenticationendpoint/identifierauth.jsp

> This PR adds missing break points to for loops added by https://github.com/wso2/reference-implementation-consumerdatastandards-au/pull/83 PR
------
7. [x] Migration scripts written (if applicable). …

Add missing break points to for loops

---

.github/workflows/create-release-tag.yaml
components/org.wso2.openbanking.cds.common/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.demo.backend/pom.xml
components/org.wso2.openbanking.cds.gateway/pom.xml
components/org.wso2.openbanking.cds.identity/pom.xml
components/org.wso2.openbanking.cds.metrics/pom.xml
components/pom.xml
integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.account.type.management.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.arrangement.revocation.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metadata.mgt.endpoint/pom.xml
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/pom.xml
internal-apis/pom.xml
pom.xml
react-apps/pom.xml
toolkits/ob-apim/pom.xml
toolkits/ob-bi/pom.xml
toolkits/ob-is/pom.xml
toolkits/pom.xml

> Bump the current maven version automatically 
> Push the commit using github bot user creds
------
8. [ ] Have you followed secure coding standards …

Fix Release Github Action to run with github bot user and automate version bumping

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/event/executor/CDSConsentEventExecutor.java
toolkits/ob-bi/carbon-home/deployment/siddhi-files/CDSAuthorisationMetricsApp.siddhi

> When authorizing a business consent involving multiple users, multiple events are triggered with identical details for different users. However, only a single event is needed to persist data into the AUTHORISATION_METRICS_DATA table. This PR ensures that duplicate entries are not persisted by preventing multiple events from being triggered within the CDSConsentEventExecutor class. The implementation is now thread-safe, ensuring consistency and preventing race conditions.
**Issue link:** 
- https://github.com/wso2/financial-services-accelerator/issues/329
------
1. [x] Built complete solution with …

Prevent Duplicate Entries in AUTHORISATION_METRICS_DATA

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/persist/CDSConsentPersistStep.java

**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/337
------
8. [x] Have you …

Fix consent amendment activating all account mappings after token revocation.

---

integration-test-suite/cds-toolkit-integration-test/pom.xml
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/AdminApiValidationTests.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/authorisation/AbandonPreAccountSelectionMetrics.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/error/ErrorMetrics_Authenticated.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/invocation_performance_averageResponse/HighPriorityMetricsValidation.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/invocation_performance_averageResponse/LargePayloadMetricsValidation.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/invocation_performance_averageResponse/LowPriorityMetricsValidation.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/invocation_performance_averageResponse/SessionCountMetricsValidation.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/invocation_performance_averageResponse/UnattendedMetricsValidation.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/invocation_performance_averageResponse/UnauthenticatedMetricsValidation.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/keymanager/test/par/RequestObjectValidationTest.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/resources/testng.xml
integration-test-suite/cds-toolkit-preconfiguration-test/pom.xml
integration-test-suite/cds-toolkit-preconfiguration-test/src/test/groovy/org/wso2/cds/preexecution/PublishAndSubscribeApiTest.groovy
integration-test-suite/cds-toolkit-preconfiguration-test/src/test/groovy/org/wso2/cds/tpponboarding/CommonTppOnboardingStep.groovy
integration-test-suite/cds-toolkit-test-framework/pom.xml
integration-test-suite/cds-toolkit-test-framework/src/main/groovy/org/wso2/cds/test/framework/constant/AUConstants.groovy
integration-test-suite/pom.xml
integration-test-suite/test-artifacts/custom-authenticator-sms-otp/identity-outbound-auth-sms-otp/pom.xml

> This PR fixes test case and build failures identified during the test suite execution.
------
8. [ ] Have you followed secure coding standards in …

Improve test cases in the test suite

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/persist/CDSConsentPersistStep.java

**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/337
------
8. [x] Have you …

Fix identifying authorizable and re-authorizable auth and mapping resources.

---

.github/workflows/maven.yaml
components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/admin/impl/CDSConsentAdminHandler.java

**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/346
------
8. [x] Have you …

Improve consent history api to return authType against account mappings

---

components/org.wso2.openbanking.cds.consent.extensions/src/main/java/org/wso2/openbanking/cds/consent/extensions/admin/impl/CDSConsentAdminHandler.java

```
{
"consentAmendmentHistory": [
{
"userList": [
{
"userId": "ann@gold.com@carbon.super",
"accounts": [
{
"accountList": [
"6500001231"
],
"authType": "linked_member"
}
]
},
{
"userId": "ann@gold.com@carbon.super",
"accounts": [
{
"accountList": [
"6500001231"
],
"authType": "linked_member"
},
{
"accountList": [
"6500001232",
"6500001231"
],
"authType": "secondary_member"
}
]
}
]
}
]
}
```
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/346
------
1. [x] Built complete solution with pull request in …

Update amendment history api response to use user list rather than a map

---

components/org.wso2.openbanking.cds.metrics/src/main/java/org/wso2/openbanking/cds/metrics/service/MetricsV5QueryCreatorImpl.java
components/org.wso2.openbanking.cds.metrics/src/test/java/org/wso2/openbanking/cds/metrics/service/MetricsV5QueryCreatorImplTest.java

Below is the existing siddhi query.
```
{
"appName" : "APIRawDataSubmissionApp", 
"query" : "from API_INVOCATION_RAW_DATA on str:contains(API_NAME, 'ConsumerDataStandards') 
select count(STATUS_CODE) as throttledOutCount, 
TIMESTAMP, 
CONSUMER_ID     
group by TIMESTAMP, 
CONSUMER_ID 
having 
STATUS_CODE == 429 and 
TIMESTAMP > 1740462033 and 
TIMESTAMP < 1741208770;"
}    
```
Below is the updated siddhi query,
```
{
"appName" : "APIRawDataSubmissionApp", 
"query" : "from API_INVOCATION_RAW_DATA on str:contains(API_NAME, 'ConsumerDataStandards') and 
STATUS_CODE == 429 and 
TIMESTAMP > 1740462033 and 
TIMESTAMP < 1841208770 
select count(STATUS_CODE) as throttledOutCount, 
TIMESTAMP, 
CONSUMER_ID group by 
TIMESTAMP, …
```

Improve rejection metrics query

---

integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/error/ErrorMetrics_Authenticated.groovy
integration-test-suite/cds-toolkit-integration-test/src/test/groovy/org/wso2/cds/integration/test/admin_api/invocation_performance_averageResponse/HighPriorityMetricsValidation.groovy
integration-test-suite/cds-toolkit-test-framework/src/main/groovy/org/wso2/cds/test/framework/AUTest.groovy
integration-test-suite/cds-toolkit-test-framework/src/main/groovy/org/wso2/cds/test/framework/utility/AUTestUtil.groovy

Please refer mail : "Including PAR endpoint as HighPriority tier for metrics calculations in CDS Toolkit"
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/369
------
7. [ ] Migration scripts written …

Update tests to include /par requests invocations in the metrics HighPriority tier.

---

components/org.wso2.openbanking.cds.common/src/main/java/org/wso2/openbanking/cds/common/config/OpenBankingCDSConfigParser.java
components/org.wso2.openbanking.cds.common/src/main/java/org/wso2/openbanking/cds/common/utils/CommonConstants.java
components/org.wso2.openbanking.cds.common/src/test/java/org/wso2/openbanking/cds/common/OpenBankingCDSConfigParserTest.java
components/org.wso2.openbanking.cds.common/src/test/resources/open-banking-cds.xml
components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/metadata/periodical/updater/internal/PeriodicalMetaDataUpdateJob.java
components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/metadata/periodical/updater/utils/Utils.java
components/org.wso2.openbanking.cds.identity/src/test/java/org/wso2/openbanking/cds/identity/metadata/periodical/updater/utils/UtilsTest.java
toolkits/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking-cds.xml.j2
toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

Below deployment.toml config is introduced to include custom headers to the CDR register API requests. Which invoked via the `PeriodicalMetaDataUpdateJob`.
```
[[open_banking_cds.metadata_cache.register_api_request.header]]
name = "x-v"
value = "2"
[[open_banking_cds.metadata_cache.register_api_request.header]]
name = "x_min_v"
value = "1"
```
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/378
------
4. …

Adding request headers for CDR register APIs.

---

components/org.wso2.openbanking.cds.consent.extensions/src/test/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/retrieval/CDSConsentRetrievalStepTests.java
components/org.wso2.openbanking.cds.gateway/src/main/java/org/wso2/openbanking/cds/gateway/mediators/GatewayErrorMediator.java

This PR fixes below issue,
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/445
------
8. [x] Have you followed secure coding standards in [WSO2 …

Fix unhandled NumberFormatException in GatewayErrorMediator

---

toolkits/ob-is/carbon-home/repository/deployment/server/webapps/ob#authenticationendpoint/oauth2_authz_displayconsent.jsp

This PR fixes below issue,
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/501
------
8. [x] Have you followed secure coding standards in [WSO2 …

Removing null params from the auth flow request

---

components/org.wso2.openbanking.cds.identity/src/test/java/org/wso2/openbanking/cds/identity/dcr/DCRUtilTest.java
components/org.wso2.openbanking.cds.metrics/src/main/java/org/wso2/openbanking/cds/metrics/util/PeriodEnum.java
internal-apis/internal-webapps/org.wso2.openbanking.cds.metrics.endpoint/src/main/java/org/wso2/openbanking/cds/metrics/endpoint/impl/MetricsApiImpl.java

This PR fixes below issue,
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/526
------
8. [x] Have you followed secure coding standards in [WSO2 …

Add validation to the enum value of `period` param in GET metrics API

---

components/org.wso2.openbanking.cds.gateway/src/main/java/org/wso2/openbanking/cds/gateway/executors/idpermanence/IDPermanenceExecutor.java

This PR fixes below issue,
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/528
------
8. [x] Have you followed secure coding standards in [WSO2 …

Handle IDPermanence request body validation error response.

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/metadata/periodical/updater/internal/PeriodicalMetaDataUpdateJob.java
components/org.wso2.openbanking.cds.identity/src/test/java/org/wso2/openbanking/cds/identity/metadata/periodical/updater/internal/PeriodicalMetaDataUpdateJobTest.java

> This pr fix the case mismatch issue when validating ADR and SP names in the metadata retrieval
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/604
------
7. [ ] Migration scripts written (if …

Fix case mismatch of ADR and SP names

---

components/org.wso2.openbanking.cds.consent.extensions/pom.xml
components/org.wso2.openbanking.cds.consent.extensions/src/test/java/org/wso2/openbanking/cds/consent/extensions/authorize/impl/persist/CDSConsentPersistStepTests.java

> Related to the changes done in the PR: https://github.com/wso2/reference-implementation-consumerdatastandards-au/pull/116
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/712
------
7. [ ] …

Improve consent extensions module unit test coverage

---

toolkits/ob-bi/carbon-home/deployment/siddhi-files/APIRawDataSubmissionApp.siddhi

> This PR resolves the inaccurate metrics issue at high TPS due to delay in persisting metrics data in the database.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/747
------
7. [ ] Migration …

Introduce a delay window to handle metrics data persisting latency

---

pom.xml

> This PR updates hibernate-validator version from 6.0.20 to 6.2.0
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/758*
------
8. [ ] Have you …

Upgrade hibernate-validator version

---

toolkits/ob-apim/carbon-home/repository/deployment/server/synapse-configs/default/sequences/jsonConverter.xml

> This PR introduces an additional condition to the jsonConverter.xml sequence to skip the GatewayErrorMediator if the error is already formatted according to the CDS Specification. It checks whether the string 'urn:au-cds:error' is present in the error response. If it is present, the GatewayErrorMediator is not engaged.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/791*
------
4. [x] Ran …

Skip the GatewayErrorMediator for already formatted errors

---

components/org.wso2.openbanking.cds.identity/src/main/java/org/wso2/openbanking/cds/identity/dcr/model/CDSRegistrationRequest.java
toolkits/ob-is/repository/resources/wso2is-6.0.0-deployment-cds.toml

> $subject
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/807*
------
8. [x] Have you followed secure coding standards in [WSO2 Secure …

Add support for authorization_signed_response_alg

---

.github/workflows/maven.yaml

> Comment Test suite execution in git action build until we resolve the base product download links.
------
8. [ ] Have you followed secure coding …

Comment Test suite execution in git action build
